routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//front (landing)
use App\Http\Controllers\Landing\LandingController;


//member (dashboard)
use App\Http\Controllers\Dashboard\MemberController;
use App\Http\Controllers\Dashboard\MyOrderController;
use App\Http\Controllers\Dashboard\ProfileController;
use App\Http\Controllers\Dashboard\RequestController;
use App\Http\Controllers\Dashboard\ServiceController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/', LandingController::class);
Route::get('detail_booking/{id}', [LandingController::class, 'detail_booking'])->name('detail.booking.landing');
Route::get('booking/{id}', [LandingController::class, 'booking'])->name('booking.landing');
Route::get('detail/{id}', [LandingController::class, 'detail'])->name('detail.landing');
Route::get('explore', [LandingController::class, 'explore'])->name('explore.landing');


Route::group(['prefix' => 'member', 'as' => 'member.', 'middleware' => ['auth:sanctum', 'verified']],
function(){

  // dashboard
  Route::resource('dashboard', MemberController::class);

  // service
  Route::resource('service', ServiceController::class);

  // request
  Route::get('approve_request/{id}', [RequestController::class, 'approve'])->name('approve.request');
  Route::resource('request', RequestController::class);

  // my order
  Route::get('reject/order/{id}', [MyOrderController::class, 'rejected'])->name('reject.order');
  Route::get('accept/order/{id}', [MyOrderController::class, 'accepted'])->name('accept.order');
  Route::resource('order', MyOrderController::class);

  // profile
  Route::get('delete_photo', [ProfileController::class, 'delete'])->name('delete.photo.profile');
  Route::resource('profile', ProfileController::class);

});


// Route::get('/', function () {
//     return view('welcome');
// });

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Http/Controllers/Dashboard/MemberController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use Auth;

use App\Models\Services;
use App\Models\Order;
use App\Models\OrderStatus;
use App\Models\User;
use App\Models\DetailUser;
use App\Models\ExperienceUser;



class MemberController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $orders = Order::where('freelance_id', Auth::user()->id)->get();

        $progress = Order::where('freelance_id', Auth::user()->id)
                        ->where('order_status_id', 2)
                        ->count();

        $completed = Order::where('freelance_id', Auth::user()->id)
                        ->where('order_status_id', 1)
                        ->count();


        $freelancer = Order::where('buyer_id', Auth::user()->id)
                        ->where('order_status_id', 2)
                        ->distinct('freelance_id')
                        ->count();


        return view('pages.dashboard.index', compact('orders', 'progress', 'completed', 'freelancer'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return abort(404);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return abort(404);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      return abort(404);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);

    }
}

app/Http/Controllers/Dashboard/MyOrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Dashboard\MyOrder\UpdateMyOrderRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use File;
use Auth;

use App\Models\Services;
use App\Models\Tagline;
use App\Models\AdvantageService;
use App\Models\AdvantageUser;
use App\Models\ThumbnailService;
use App\Models\Order;
use App\Models\OrderStatus;
use App\Models\User;

class MyOrderController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $orders = Order::where('freelance_id', Auth::user()->id)
                    ->orderBy('created_at', 'desc')
                    ->get();
        return view('pages.dashboard.order.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)//parameter by Model Order
    {
      $service = Services::where('id', $order['service_id'])->first();
      $thumbnail = ThumbnailService::where('service_id', $order['service_id'])->get();
      $tagline = Tagline::where('service_id', $order['service_id'])->get();
      $advantage_service = AdvantageService::where('service_id', $order['service_id'])->get();
      $advantage_user = AdvantageUser::where('service_id', $order['service_id'])->get();
      return view('pages.dashboard.order.detail', compact('service', 'thumbnail', 'tagline', 'advantage_user', 'advantage_service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
      return view('pages.dashboard.order.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMyOrderRequest $request, Order $order)
    {
        $data = $request->all();

        if (isset($data['file'])) {
          $data['file'] = $request->file('file')->store(
            'assets/order/attachment', 'public'
          );
        }

        $order = Order::find($order->id);
        $order->file = $data['file'];
        $order->note = $data['note'];
        $order->save();

        toast()->success('Submit order has been success');
        return redirect()->route('member.order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);
    }

    // custom

    public function accepted($id)
    {
      $order = Order::find($id);
      $order->order_status_id = 2;
      $order->save();
      toast()->success('Accept order has been success');
      return back();
    }

    public function rejected($id)
    {
      $order = Order::find($id);
      $order->order_status_id = 3;
      $order->save();
      toast()->success('Reject order has been success');
      return back();
    }
}

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Dashboard\Profile\UpdateDetailUserRequest;
use App\Http\Requests\Dashboard\Profile\UpdateProfileRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use File;
use Auth;


use App\Models\User;
use App\Models\DetailUser;
use App\Models\ExperienceUser;


class ProfileController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::where('id', Auth::user()->id)->first();
        $experienceUser = ExperienceUser::where('detail_user_id', $user->detail_user->id)
                                          ->orderBy('id','asc')
                                          ->get();
        return view('pages.dashboard.profile', compact('user', 'experienceUser'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return abort(404);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProfileRequest $request_profile, UpdateDetailUserRequest $request_detail_user)
    {
        $data_profile     = $request_profile->all();
        $data_detail_user = $request_detail_user->all();

        //get Photo
        $get_photo = DetailUser::where('users_id', Auth::user()->id)->first();

        //detele old photo
        if (isset($data_detail_user['photo'])) {
          $data =  'storage/'.$get_photo['photo'];
            if (File::exists($data)) {
              File::delete($data);
            }else {
              //detail delete
              File::delete('storage/app/public/'.$get_photo['photo']);
            }
        }


        //store photo to storage
        if (isset($data_detail_user['photo'])) {
          $data_detail_user['photo'] = $request_detail_user->file('photo')
                                                           ->store('assets/images', 'public');
        }

        //proccess saving/updating to users
        $user = User::find(Auth::user()->id);
        $user->update($data_profile);

        //proccess saving/updating to detail user
        $detail_user = DetailUser::find($user->detail_user->id);
        $detail_user->update($data_detail_user);

        //proccess saving/updating to experience user
        $experienceUserId = ExperienceUser::where('detail_user_id',$detail_user->id)->first();
        if (isset($experienceUserId)) {

          foreach ($data_profile['experience'] as $key => $value) {
              $experienceUser = ExperienceUser::find($key);
              $experienceUser->detail_user_id = $detail_user['id'];
              $experienceUser->experience = $value;
              $experienceUser->save();
          }
          //endforeach

        }else{

          foreach ($data_profile['experience'] as $key => $value) {

            if (isset($value)) {
              $experienceUser = new ExperienceUser;
              $experienceUser->detail_user_id = $detail_user['id'];
              $experienceUser->experience = $value;
              $experienceUser->save();
            }
            //endif
          }
          //endforeach
        }
        //end if else

        //alert
        toast()->success('Update Has Been Success');
        return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);
    }

    // custom

    public function delete()
    {
      //get User Photo
      $get_user_photo = DetailUser::where('users_id', Auth::user()->id)->first();
      $path_photo = $get_user_photo['photo'];

      // second update value to null
      $data = DetailUser::find($get_user_photo['id']);
      $data->photo = NULL;
      $data->save();

      //delete file photo on storage
      $path = 'storage/'.$path_photo;
      if (File::exists($path)) {

        File::delete($path);

      }else {
        //detail delete
        File::delete('storage/app/public/'.$path_photo);

      }
      //endif

      //alert
      toast()->success('Delete Has Been Success');
      return back();

    }

}

app/Http/Controllers/Dashboard/RequestController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use File;
use Auth;

use App\Models\Services;
use App\Models\Order;
use App\Models\User;
use App\Models\OrderStatus;


class RequestController extends Controller
{
    public function __construct()
    {
      $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::where('buyer_id', Auth::user()->id)
                      ->orderBy('created_at', 'desc')
                      ->get();
        return view('pages.dashboard.request.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      //detail
      $order = Order::where('id', $id)->first();

      return view('pages.dashboard.request.detail', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      return abort(404);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);

    }


    // custom

    public function approve($id)
    {
      $orders = Order::where('id', $id)->first();


      //update orders
      $update_order = Order::find($orders['id']);
      $update_order->order_status_id = 1;
      $update_order->save();

      toast()->success('Approve has been success');
      return redirect()->route('member.request.index');
    }
}

resources/views/pages/dashboard/order/index.blade.php
@extends('layouts.app')

@section('title', 'My Orders')

@section('content')

  <main class="h-full overflow-y-auto">
      <div class="container mx-auto">
          <div class="grid w-full gap-5 px-10 mx-auto md:grid-cols-12">
              <div class="col-span-8">
                  <h2 class="mt-8 mb-1 text-2xl font-semibold text-gray-700">
                      My Orders
                  </h2>
                  <p class="text-sm text-gray-400">
                      {{ auth()->user()->order_freelancer()->count()}} Total Orders
                  </p>
              </div>
              <div class="col-span-4 lg:text-right">

              </div>
          </div>
      </div>
      <section class="container px-6 mx-auto mt-5">
          <div class="grid gap-5 md:grid-cols-12">
              <main class="col-span-12 p-4 md:pt-0">
                  <div class="px-6 py-2 mt-2 bg-white rounded-xl">
                      <table class="w-full" aria-label="Table">
                          <thead>
                              <tr class="text-sm font-normal text-left text-gray-900 border-b border-b-gray-600">
                                  <th class="py-4" scope="">Buyers Name</th>
                                  <th class="py-4" scope="">Service Details</th>
                                  <th class="py-4" scope="">Expires</th>
                                  <th class="py-4" scope="">Action</th>
                              </tr>
                          </thead>
                          <tbody class="bg-white">
                            @forelse ($orders as $item)
                              <tr class="text-gray-700 border-b">
                                  <td class="px-1 py-5 text-sm w-2/8">
                                      <div class="flex items-center text-sm">
                                          <div class="relative w-10 h-10 mr-3 rounded-full md:block">
                                            @if ($item->user_buyer->detail_user->photo != NULL)
                                              <img class="object-cover w-full h-full rounded-full" src="{{ url(Storage::url($item->user_buyer->detail_user->photo ))}}" alt="" loading="lazy" />
                                            @else
                                              {{-- empty --}}
                                            @endif
                                              <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                                          </div>
                                          <div>
                                              <p class="font-medium text-black">{{ $item->user_buyer->name ?? '' }}</p>
                                              <p class="text-sm text-gray-400">{{ $item->user_buyer->detail_user->role ?? '' }}</p>
                                          </div>
                                      </div>
                                  </td>
                                  <td class="w-2/6 px-1 py-5">
                                      <div class="flex items-center text-sm">
                                          <div class="relative w-10 h-10 mr-3 rounded-full md:block">
                                            @if ($item->service->thumbnail_service[0]->thumbnail != NULL)
                                              <img class="object-cover w-full h-full rounded-full" src="{{ url(Storage::url($item->service->thumbnail_service[0]->thumbnail))}}" alt="" loading="lazy" />
                                            @else
                                              {{-- empty --}}
                                            @endif
                                              <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                                          </div>
                                          <div>
                                              <p class="font-medium text-black">
                                                  {{ $item->service->title ?? '' }}
                                              </p>
                                          </div>
                                      </div>
                                  </td>

                                  <td class="px-1 py-5 text-xs text-red-500">
                                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="inline mb-1">
                                          <path d="M7.0002 12.8332C10.2219 12.8332 12.8335 10.2215 12.8335 6.99984C12.8335 3.77818 10.2219 1.1665 7.0002 1.1665C3.77854 1.1665 1.16687 3.77818 1.16687 6.99984C1.16687 10.2215 3.77854 12.8332 7.0002 12.8332Z" stroke="#F26E6E" stroke-linecap="round" stroke-linejoin="round" />
                                          <path d="M7 3.5V7L9.33333 8.16667" stroke="#F26E6E" stroke-linecap="round" stroke-linejoin="round" />
                                      </svg>
                                      {{ (strtotime($item->expired) - strtotime(date('Y-m-d'))) /86400 ??'' }} days left
                                  </td>
                                  <td class="px-1 py-5 text-sm">
                                    @if ($item->order_status_id == 1)
                                      <a href="{{ route('member.order.show', $item->id)}}" class="px-4 py-2 mt-1 mr-2 text-center text-white rounded-xl bg-serv-email">
                                          Details
                                      </a>
                                      <p class="px-4 py-2 mt-2 inline text-left text-green-500">
                                        Approve
                                      </p>
                                    @elseif ($item->order_status_id == 2)
                                      <a href="{{ route('member.order.show', $item->id)}}" class="px-4 py-2 mt-1 mr-2 text-center text-white rounded-xl bg-serv-email">
                                          Details
                                      </a>
                                      <a href="{{ route('member.order.edit', $item->id)}}" class="px-4 py-2 mt-1 mr-2 text-center text-white rounded-xl bg-serv-email">
                                          Submit
                                      </a>
                                    @elseif ($item->order_status_id == 3)
                                      <a href="{{ route('member.order.show', $item->id)}}" class="px-4 py-2 mt-1 mr-2 text-center text-white rounded-xl bg-serv-email">
                                          Details
                                      </a>
                                      <p class="px-4 py-2 mt-2 inline text-left text-red-500">
                                        Rejected
                                      </p>
                                    @elseif ($item->order_status_id == 4)
                                      <a href="{{ route('member.accept.order', $item->id)}}" class="px-4 py-2 mt-1 mr-2 text-center text-white rounded-xl bg-serv-button">
                                          Accept
                                      </a>
                                      <a href="{{ route('member.reject.order', $item->id)}}" class="px-4 py-2 mt-1 mr-2 text-left bg-white rounded-xl">
                                          Reject
                                      </a>

                                    @else
                                      {{ "N/A" }}
                                    @endif
                                  </td>
                              </tr>
                            @empty

                            @endforelse


                          </tbody>
                      </table>
                  </div>
              </main>
          </div>
      </section>
  </main>

@endsection