routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//front (landing)
use App\Http\Controllers\Landing\LandingController;


//member (dashboard)
use App\Http\Controllers\Dashboard\MemberController;
use App\Http\Controllers\Dashboard\MyOrderController;
use App\Http\Controllers\Dashboard\ProfileController;
use App\Http\Controllers\Dashboard\RequestController;
use App\Http\Controllers\Dashboard\ServiceController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/', LandingController::class);
Route::get('detail_booking/{id}', [LandingController::class, 'detail_booking'])->name('detail.booking.landing');
Route::get('booking/{id}', [LandingController::class, 'booking'])->name('booking.landing');
Route::get('detail/{id}', [LandingController::class, 'detail'])->name('detail.landing');
Route::get('explore', [LandingController::class, 'explore'])->name('explore.landing');


Route::group(['prefix' => 'member', 'as' => 'member.', 'middleware' => ['auth:sanctum', 'verified']],
function(){

  // dashboard
  Route::resource('dashboard', MemberController::class);

  // service
  Route::resource('service', ServiceController::class);

  // request
  Route::get('approve_request/{id}', [RequestController::class, 'approve'])->name('approve.request');
  Route::resource('request', RequestController::class);

  // my order
  Route::get('reject/order/{id}', [MyOrderController::class, 'rejected'])->name('reject.order');
  Route::get('accept/order/{id}', [MyOrderController::class, 'accepted'])->name('accept.order');
  Route::resource('order', MyOrderController::class);

  // profile
  Route::get('delete_photo', [ProfileController::class, 'delete'])->name('delete.photo.profile');
  Route::resource('profile', ProfileController::class);

});


// Route::get('/', function () {
//     return view('welcome');
// });

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Http/Controllers/Dashboard/MemberController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use Auth;

use App\Models\Services;
use App\Models\Order;
use App\Models\OrderStatus;
use App\Models\User;
use App\Models\DetailUser;
use App\Models\ExperienceUser;



class MemberController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $orders = Order::where('freelance_id', Auth::user()->id)->get();

        $progress = Order::where('freelance_id', Auth::user()->id)
                        ->where('order_status_id', 2)
                        ->count();

        $completed = Order::where('freelance_id', Auth::user()->id)
                        ->where('order_status_id', 1)
                        ->count();


        $freelancer = Order::where('buyer_id', Auth::user()->id)
                        ->where('order_status_id', 2)
                        ->distinct('freelance_id')
                        ->count();


        return view('pages.dashboard.index', compact('orders', 'progress', 'completed', 'freelancer'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return abort(404);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return abort(404);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      return abort(404);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);

    }
}

app/Http/Controllers/Dashboard/MyOrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Dashboard\MyOrder\UpdateMyOrderRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use File;
use Auth;

use App\Models\Services;
use App\Models\Tagline;
use App\Models\AdvantageService;
use App\Models\AdvantageUser;
use App\Models\ThumbnailService;
use App\Models\Order;
use App\Models\OrderStatus;
use App\Models\User;

class MyOrderController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $orders = Order::where('freelance_id', Auth::user()->id)
                    ->orderBy('created_at', 'desc')
                    ->get();
        return view('pages.dashboard.order.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)//parameter by Model Order
    {
      $service = Services::where('id', $order['service_id'])->first();
      $thumbnail = ThumbnailService::where('service_id', $order['service_id'])->get();
      $tagline = Tagline::where('service_id', $order['service_id'])->get();
      $advantage_service = AdvantageService::where('service_id', $order['service_id'])->get();
      $advantage_user = AdvantageUser::where('service_id', $order['service_id'])->get();
      return view('pages.dashboard.order.detail', compact('service', 'thumbnail', 'tagline', 'advantage_user', 'advantage_service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
      return view('pages.dashboard.order.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMyOrderRequest $request, Order $order)
    {
        $data = $request->all();

        if (isset($data['file'])) {
          $data['file'] = $request->file('file')->store(
            'assets/order/attachment', 'public'
          );
        }

        $order = Order::find($order->id);
        $order->file = $data['file'];
        $order->note = $data['note'];
        $order->save();

        toast()->success('Submit order has been success');
        return redirect()->route('member.order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);
    }

    // custom

    public function accepted($id)
    {
      $order = Order::find($id);
      $order->order_status_id = 2;
      $order->save();
      toast()->success('Accept order has been success');
      return back();
    }

    public function rejected($id)
    {
      $order = Order::find($id);
      $order->order_status_id = 3;
      $order->save();
      toast()->success('Reject order has been success');
      return back();
    }
}

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Dashboard\Profile\UpdateDetailUserRequest;
use App\Http\Requests\Dashboard\Profile\UpdateProfileRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use File;
use Auth;


use App\Models\User;
use App\Models\DetailUser;
use App\Models\ExperienceUser;


class ProfileController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::where('id', Auth::user()->id)->first();
        $experienceUser = ExperienceUser::where('detail_user_id', $user->detail_user->id)
                                          ->orderBy('id','asc')
                                          ->get();
        return view('pages.dashboard.profile', compact('user', 'experienceUser'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return abort(404);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProfileRequest $request_profile, UpdateDetailUserRequest $request_detail_user)
    {
        $data_profile     = $request_profile->all();
        $data_detail_user = $request_detail_user->all();

        //get Photo
        $get_photo = DetailUser::where('users_id', Auth::user()->id)->first();

        //detele old photo
        if (isset($data_detail_user['photo'])) {
          $data =  'storage/'.$get_photo['photo'];
            if (File::exists($data)) {
              File::delete($data);
            }else {
              //detail delete
              File::delete('storage/app/public/'.$get_photo['photo']);
            }
        }


        //store photo to storage
        if (isset($data_detail_user['photo'])) {
          $data_detail_user['photo'] = $request_detail_user->file('photo')
                                                           ->store('assets/images', 'public');
        }

        //proccess saving/updating to users
        $user = User::find(Auth::user()->id);
        $user->update($data_profile);

        //proccess saving/updating to detail user
        $detail_user = DetailUser::find($user->detail_user->id);
        $detail_user->update($data_detail_user);

        //proccess saving/updating to experience user
        $experienceUserId = ExperienceUser::where('detail_user_id',$detail_user->id)->first();
        if (isset($experienceUserId)) {

          foreach ($data_profile['experience'] as $key => $value) {
              $experienceUser = ExperienceUser::find($key);
              $experienceUser->detail_user_id = $detail_user['id'];
              $experienceUser->experience = $value;
              $experienceUser->save();
          }
          //endforeach

        }else{

          foreach ($data_profile['experience'] as $key => $value) {

            if (isset($value)) {
              $experienceUser = new ExperienceUser;
              $experienceUser->detail_user_id = $detail_user['id'];
              $experienceUser->experience = $value;
              $experienceUser->save();
            }
            //endif
          }
          //endforeach
        }
        //end if else

        //alert
        toast()->success('Update Has Been Success');
        return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);
    }

    // custom

    public function delete()
    {
      //get User Photo
      $get_user_photo = DetailUser::where('users_id', Auth::user()->id)->first();
      $path_photo = $get_user_photo['photo'];

      // second update value to null
      $data = DetailUser::find($get_user_photo['id']);
      $data->photo = NULL;
      $data->save();

      //delete file photo on storage
      $path = 'storage/'.$path_photo;
      if (File::exists($path)) {

        File::delete($path);

      }else {
        //detail delete
        File::delete('storage/app/public/'.$path_photo);

      }
      //endif

      //alert
      toast()->success('Delete Has Been Success');
      return back();

    }

}

app/Http/Controllers/Dashboard/RequestController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

use File;
use Auth;

use App\Models\Services;
use App\Models\Order;
use App\Models\User;
use App\Models\OrderStatus;


class RequestController extends Controller
{
    public function __construct()
    {
      $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::where('buyer_id', Auth::user()->id)
                      ->orderBy('created_at', 'desc')
                      ->get();
        return view('pages.dashboard.request.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      //detail
      $order = Order::where('id', $id)->first();

      return view('pages.dashboard.request.detail', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      return abort(404);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      return abort(404);

    }


    // custom

    public function approve($id)
    {
      $orders = Order::where('id', $id)->first();


      //update orders
      $update_order = Order::find($orders['id']);
      $update_order->order_status_id = 1;
      $update_order->save();

      toast()->success('Approve has been success');
      return redirect()->route('member.request.index');
    }
}

resources/views/pages/dashboard/profile.blade.php
@extends('layouts.app')

@section('title','Edit Profile')

@section('content')

  <main class="h-full overflow-y-auto">
      <div class="container mx-auto">
          <div class="grid w-full gap-5 px-10 mx-auto md:grid-cols-12">
              <div class="col-span-12">
                  <h2 class="mt-8 mb-1 text-2xl font-semibold text-gray-700">
                      Edit My Profile
                  </h2>
                  <p class="text-sm text-gray-400">
                      Enter your data Correctly & Properly
                  </p>
              </div>
          </div>
      </div>
      <section class="container px-6 mx-auto mt-5">
          <div class="grid gap-5 md:grid-cols-12">
              <main class="col-span-12 p-4 md:pt-0">
                  <div class="px-2 py-2 mt-2 bg-white rounded-xl">

                        <form action="{{ route('member.profile.update', [Auth::user()->id]) }}" method="POST" enctype="multipart/form-data">
                
                        @method('PUT')
                        @csrf
                          <div class="">
                              <div class="px-4 py-5 sm:p-6">
                                  <div class="grid grid-cols-6 gap-6">
                                      <div class="col-span-6">
                                          <div class="flex items-center mt-1">
                                            @if (auth()->user()->detail_user()->first()->photo != NULL)
                                              <img src="{{ url(Storage::url(auth()->user()->detail_user()->first()->photo)) }}" alt="photo-profile" class="rounded-full  w-16 h-16">

                                            @else

                                              <span class="inline-block w-16 h-16 overflow-hidden bg-gray-100 rounded-full">
                                                  <svg class="w-full h-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
                                                      <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                                                  </svg>
                                              </span>

                                            @endif

                                            <label for="choose" class="px-3 py-2 ml-5 text-sm font-medium leading-4 text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">  Choose File</label>

                                            <input type="file" accept="image/*" id="choose" name="photo" value="" hidden>

                                            <a  href="{{ route('member.delete.photo.profile') }}" type="button" class="px-3 py-2 ml-5 text-sm font-medium leading-4 text-red-700 bg-transparent rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" onclick="return confirm('are you sure want to delete your photo?')">
                                                Delete
                                            </a>

                                          </div>

                                          @if ($errors->has('photo'))

                                            <p class="text-red-500 mb-3 text-sm">{{ $errors->first('photo') }}</p>

                                          @endif

                                      </div>
                                      <div class="md:col-span-6 lg:col-span-3">
                                          <label for="name" class="block mb-3 font-medium text-gray-700 text-md">Full Name</label>
                                          <input placeholder="Your Name" type="text" name="name" id="name" autocomplete="name" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm" value="{{ $user->name ?? ''}}" required>
                                          @if ($errors->has('name'))

                                            <p class="text-red-500 mb-3 text-sm">{{ $errors->first('name') }}</p>

                                          @endif
                                      </div>
                                      <div class="md:col-span-6 lg:col-span-3">
                                          <label for="role" class="block mb-3 font-medium text-gray-700 text-md">Role</label>
                                          <input placeholder="Your Role" type="text" name="role" id="role" autocomplete="role" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm" value="{{ $user->detail_user->role ?? '' }}" required>
                                          @if ($errors->has('role'))

                                            <p class="text-red-500 mb-3 text-sm">{{ $errors->first('role') }}</p>

                                          @endif
                                      </div>
                                      <div class="md:col-span-6 lg:col-span-3">
                                          <label for="email" class="block mb-3 font-medium text-gray-700 text-md">Email Address</label>
                                          <input placeholder="Your Email Address" type="email" name="email" id="email" autocomplete="email" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm" value="{{ $user->email ?? '' }}" required>
                                          @if ($errors->has('email'))

                                            <p class="text-red-500 mb-3 text-sm">{{ $errors->first('email') }}</p>

                                          @endif
                                      </div>
                                      <div class="md:col-span-6 lg:col-span-3">
                                          <label for="contact_number" class="block mb-3 font-medium text-gray-700 text-md">Contact Number</label>
                                          <input placeholder="Your Contact Number" type="number" name="contact_number" id="contact_number" autocomplete="contact_number" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm" value="{{ $user->detail_user->contact_number ?? '' }}" required>
                                          @if ($errors->has('contact_number'))

                                            <p class="text-red-500 mb-3 text-sm">{{ $errors->first('contact_number') }}</p>

                                          @endif
                                      </div>
                                      <div class="col-span-6">
                                          <label for="biography" class="block mb-3 font-medium text-gray-700 text-md">Biografi</label>
                                          <textarea placeholder="Enter your biography here.." type="text" name="biography" id="biography" autocomplete="biography" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm" rows="4">{{ $user->detail_user->biography ?? '' }}</textarea>
                                          @if ($errors->has('biography'))

                                            <p class="text-red-500 mb-3 text-sm">{{ $errors->first('biography') }}</p>

                                          @endif
                                      </div>
                                      <div class="col-span-6">
                                          <label for="experience" class="block mb-3 font-medium text-gray-700 text-md">My Experience</label>
                                          @forelse ($experienceUser as $key => $item)
                                            <input placeholder="More than 9 years of experience" type="text" name="{{'experience['.$item->id.']'}}" id="{{'experience['.$item->id.']'}}" autocomplete="{{'experience['.$item->id.']'}}" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm" value="{{ $item->experience }}">
                                            @if ($errors->has('experience['.$item->id.']'))

                                              <p class="text-red-500 mb-3 text-sm">{{ $errors->first('experience') }}</p>

                                            @endif
                                          @empty
                                            <input placeholder="Lead Developer at Sony Music for 8 Years" type="text" name="experience[]" id="experience" autocomplete="experience" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm">
                                            @if ($errors->has('experience'))

                                              <p class="text-red-500 mb-3 text-sm">{{ $errors->first('experience') }}</p>

                                            @endif

                                            <input placeholder="Lead Developer at Sony Music for 8 Years" type="text" name="experience[]" id="experience" autocomplete="experience" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm">
                                            @if ($errors->has('experience'))

                                              <p class="text-red-500 mb-3 text-sm">{{ $errors->first('experience') }}</p>

                                            @endif

                                            <input placeholder="Lead Developer at Sony Music for 8 Years" type="text" name="experience[]" id="experience" autocomplete="experience" class="block w-full py-3 mt-1 border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500 sm:text-sm">
                                            @if ($errors->has('experience'))

                                              <p class="text-red-500 mb-3 text-sm">{{ $errors->first('experience') }}</p>

                                            @endif
                                          @endforelse
                                      </div>
                                  </div>
                              </div>
                              <div class="px-4 py-3 text-right sm:px-6">
                                  <a href="{{ route('member.dashboard.index') }}" type="button" class="inline-flex justify-center px-4 py-2 mr-4 text-sm font-medium text-gray-700 bg-white border border-gray-600 rounded-lg shadow-sm hover:bg-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-300" onclick="return confirm('Are you sure to cancel? Any change you make will not be saved')">
                                      Cancel
                                  </a>
                                  <button type="submit" class="inline-flex justify-center px-4 py-2 text-sm font-medium text-white bg-green-600 border border-transparent rounded-lg shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" onclick="return confirm
                                  ('Are you sure want to submit this data')">
                                      Save Changes
                                  </button>
                              </div>
                          </div>
                      </form>

                  </div>
              </main>
          </div>
      </section>
  </main>


@endsection